---
version: '3.7'
services:
  app:
    image: "${DOCKER_ORGANIZATION}/${DOCKER_REPOSITORY}:${DOCKER_TAG}"
    environment:
      RAILS_LOG_TO_STDOUT: '1'
      RAILS_SERVE_STATIC_FILES: '1'
      WEB_PRELOAD_APP: '1'
      WEB_HEALTHCHECK_PATH: "/"
      DATABASE_URL: 
      HOST_UID: 
      RAILS_ENV: 
      SECRET_KEY_BASE: 
      WEB_CONCURRENCY: 
      WEB_TIMEOUT: 
      WEB_WORKER_PROCESSES: 
    ports:
    - "${CONTAINER_PORT:?CONTAINER_PORT must be provided}:8080"
    deploy:
      mode: replicated
      replicas: "${REPLICAS}"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
volumes: {}
